Repository ICE-AdvICE/advICE-web, pull requests merged in 2025-08, with the labels that each got.

#241 [BE-#238] 조교 권한 부여/박탈 로직 수정
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/controller/AuthorityController.java
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/controller/EntireAdminController.java
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/domain/entity/Authority.java
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/repostiory/AuthorityRepository.java
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/scheduler/AdminScheduler.java
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/service/AuthorityService.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/CodingZoneService.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/implement/CodingZoneServiceImplement.java
Labels: refactor

#246 [BE-#233] 교과목에 해당하는 조교 리스트를 반환하는 비지니스 로직 추가
  backend/src/main/java/com/icehufs/icebreaker/common/ResponseCode.java
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/controller/EntireAdminController.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/response/AssistantNamesResponseDto.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/CodingZoneService.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/implement/CodingZoneServiceImplement.java
Labels: feat

#260 [BE-#259] Member 도메인 네이밍 변경 및 예외 객체 추가
  backend/src/main/java/com/icehufs/icebreaker/common/ResponseCode.java
  backend/src/main/java/com/icehufs/icebreaker/domain/membership/controller/UserController.java
  backend/src/main/java/com/icehufs/icebreaker/domain/membership/domain/entity/User.java
  backend/src/main/java/com/icehufs/icebreaker/domain/membership/domain/exception/DuplicatePasswordException.java
  backend/src/main/java/com/icehufs/icebreaker/domain/membership/domain/exception/UserNotFoundException.java
  backend/src/main/java/com/icehufs/icebreaker/domain/membership/dto/request/AuthorityRequestDto.java
  backend/src/main/java/com/icehufs/icebreaker/domain/membership/dto/request/ChangeUserInfoRequestDto.java
  backend/src/main/java/com/icehufs/icebreaker/domain/membership/dto/request/ChangeUserPasswordRequestDto.java
  backend/src/main/java/com/icehufs/icebreaker/domain/membership/dto/response/GetSignInUserResponseDto.java
  backend/src/main/java/com/icehufs/icebreaker/domain/membership/dto/response/GetUserInfoResponseDto.java
  backend/src/main/java/com/icehufs/icebreaker/domain/membership/repository/UserRepository.java
  backend/src/main/java/com/icehufs/icebreaker/domain/membership/service/UserService.java
  backend/src/main/java/com/icehufs/icebreaker/domain/membership/service/implement/UserServiceImplement.java
Labels: refactor

#250 [FE-#249] 배너 모듈화 및 헤더 CSS 수정
  frontend/src/pages/Coding-zone/CodingZoneAttendanceAssistant.js
  frontend/src/pages/Coding-zone/CodingZoneAttendanceManager.js
  frontend/src/pages/Coding-zone/CodingZoneMain.js
  frontend/src/pages/Coding-zone/CodingZoneMyAttendance.js
  frontend/src/pages/Coding-zone/CodingZoneRegist.js
  frontend/src/pages/css/codingzone/codingzone_attend.css
  frontend/src/shared/ui/Banner/Banner.css
  frontend/src/shared/ui/Banner/Banner.js
  frontend/src/shared/ui/Banner/BannerSlider.js
  frontend/src/widgets/layout/Header/Navbar.css
  frontend/src/widgets/layout/Header/Navbar.js
Labels: refactor, design

#281 [BE-#255] 특정 날짜, 특정 교과목으로 등록한 코딩존 수업 정보 리스트 반환 비지니스 로직 작성
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/controller/SubjectController.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/domain/entity/CodingZoneClass.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/response/CodingZoneClassInfoResponseDto.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/repository/CodingZoneClassRepository.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/CodingZoneService.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/implement/CodingZoneServiceImplement.java
Labels: feat

#282 [FE-#276] 기존의 조 등록과 수업 등록 기능 병합
  frontend/src/pages/Coding-zone/CodingZoneRegist.js
Labels: refactor, feat

#301 [FE-#271] 레이아웃 및 CSS 수정
  frontend/src/shared/ui/Banner/Banner.css
  frontend/src/shared/ui/boardbar/CodingZoneBoardbar.css
  frontend/src/shared/ui/boardbar/CodingZoneBoardbar.js
  frontend/src/shared/ui/navigation/CodingZoneNavigation.css
  frontend/src/shared/ui/navigation/CodingZoneNavigation.js
  frontend/src/widgets/layout/Header/Navbar.css
  frontend/src/widgets/layout/Header/Navbar.js
Labels: refactor, design

#309 [BE-#304] 코딩존 특정 수업 삭제 API 리펙토링
  backend/src/main/java/com/icehufs/icebreaker/common/ResponseCode.java
  backend/src/main/java/com/icehufs/icebreaker/common/ResponseMessage.java
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/controller/ClassAndGroupManageController.java
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/controller/EntireAdminController.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/exception/CodingZoneClassNotFoundException.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/exception/ExistCodingZoneRegisterException.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/repository/CodingZoneRegisterRepository.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/CodingZoneClassService.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/CodingZoneService.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/implement/CodingZoneServiceImplement.java
  backend/src/main/resources/application.properties
Labels: refactor

#310 [FE-#300] 수업 등록 페이지 디자인 수정
  frontend/src/pages/Coding-zone/CodingZoneRegist.js
  frontend/src/pages/css/codingzone/CodingClassRegist.css
Labels: design

#311 [BE-#294] 학기 초기화 API 리펙토링
  backend/build/resources/main/application.properties
  backend/src/main/java/com/icehufs/icebreaker/common/ResponseMessage.java
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/controller/EntireAdminController.java
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/controller/SemesterMaintenanceController.java
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/repostiory/AuthorityRepository.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/CodingZoneService.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/SemesterMaintenanceService.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/implement/CodingZoneServiceImplement.java
  backend/src/main/resources/application.properties
Labels: refactor

#315 [BE-#286] 날짜에 해당하는 코딩존 반환 api 수정
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/controller/EntireAdminController.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/response/SubjectMappingInfoResponseDto.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/CodingZoneService.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/implement/CodingZoneServiceImplement.java
Labels: bug

#332 [BE-#256] 출결 체크 로직 수정
  backend/src/main/java/com/icehufs/icebreaker/common/ResponseCode.java
  backend/src/main/java/com/icehufs/icebreaker/common/ResponseMessage.java
  backend/src/main/java/com/icehufs/icebreaker/config/WebSecurityConfig.java
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/controller/CodingZoneClass1Controller.java
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/controller/CodingZoneClass2Controller.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/controller/AdminCodingZoneController.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/domain/entity/CodingZoneRegister.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/repository/CodingZoneRegisterRepository.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/AttendanceService.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/CodingZoneService.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/implement/CodingZoneServiceImplement.java
  backend/src/main/java/com/icehufs/icebreaker/filter/JwtAuthenticationFilter.java
Labels: feat

#336 fix : import 문 수정
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/AttendanceService.java
Labels: bug

#331 [FE-#329] API 수정하면서 수정 못한 페이지 수정
  frontend/src/pages/AuthHandle.js
  frontend/src/pages/Coding-zone/CodingZoneRegist.js
  frontend/src/pages/Coding-zone/CodingZoneSetting.js
Labels: bug

#338 [BE-#337] 코딩존 조교 별 특정 날짜에 해당하는 수업 예약한 학생 리스트 반환 api 구현
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/domain/entity/Authority.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/controller/AdminCodingZoneController.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/response/RegisterInfoResponseDto.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/repository/CodingZoneClassRepository.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/AttendanceService.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/implement/CodingZoneServiceImplement.java
Labels: feat

#345 fix : findCodingZoneClassesBySubjectAndDate() 내 NPE 방지를 위한 방어적 null check 적용
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/repository/GroupInfRepository.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/implement/CodingZoneServiceImplement.java
Labels: bug

#347 [FE-#326] 출결관리 수업 리스트 반환
  frontend/src/app/App.js
  frontend/src/entities/api/CodingZone/AdminApi.js
  frontend/src/pages/Coding-zone/CodingZoneAttendanceAssistant.js
  frontend/src/pages/Coding-zone/CodingZoneAttendanceEA.js
  frontend/src/pages/css/codingzone/codingzone_attend.css
  frontend/src/shared/ui/boardbar/CodingZoneBoardbar.js
Labels: feat, design

#354 [FE-#348] 출결관리 학생 리스트 반환
  frontend/src/entities/api/CodingZone/AdminApi.js
  frontend/src/features/api/Admin/Codingzone/AttendanceApi.js
  frontend/src/pages/Coding-zone/CodingZoneAttendanceAssistant.js
  frontend/src/pages/Coding-zone/CodingZoneAttendanceEA.js
  frontend/src/pages/css/codingzone/codingzone_attend.css
  frontend/src/pages/css/codingzone/codingzone_manager.css
Labels: feat, design

#358 [FE-#355] API 수정
  frontend/src/features/api/Admin/Codingzone/ClassApi.js
  frontend/src/pages/Coding-zone/CodingZoneAttendanceAssistant.js
  frontend/src/pages/Coding-zone/CodingZoneAttendanceEA.js
  frontend/src/shared/ui/navigation/CodingZoneNavigation.js
Labels: feat

#361 [FE-#359] 조 버튼 색상 수정
  frontend/src/pages/css/codingzone/CodingClassRegist.css
Labels: design

#364 fix : 과사 조교 - 특정 과목 , 날짜에 해당하는 코딩존 목록 반환 api 수정
  backend/src/main/java/com/icehufs/icebreaker/domain/auth/controller/AdminSubjectController.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/response/CodingZoneClassInfoResponseDto.java
  backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/implement/CodingZoneServiceImplement.java
Labels: bug

#367 [FE-#362] 코딩존 등록 현황 리스트 조회 (과사조교)
  frontend/public/left.png
  frontend/public/leftnone.png
  frontend/src/pages/Coding-zone/CodingZoneMain.js
  frontend/src/pages/css/codingzone/codingzone-main.css
  frontend/src/pages/css/codingzone/codingzone_attend.css
  frontend/src/shared/lib/codingzoneStatus.js
  frontend/src/widgets/CodingZone/SubjectClassesTable.css
  frontend/src/widgets/CodingZone/SubjectClassesTable.jsx
Labels: feat, design

#369 [FE-#368] 코딩존 등록 현황 리스트 단건 삭제 구현 (과사조교)
  frontend/src/entities/api/CodingZone/AdminApi.js
  frontend/src/pages/Coding-zone/CodingZoneMain.js
  frontend/src/widgets/CodingZone/SubjectClassesTable.css
  frontend/src/widgets/CodingZone/SubjectClassesTable.jsx
Labels: feat, design

#375 [FE-#373] 코딩존 예약 페이지(일반 학생) 예약 기능 및 출석 횟수 조회 API 연동
  frontend/src/entities/api/CodingZone/StudentApi.js
  frontend/src/pages/Coding-zone/CodingZoneMain.js
  frontend/src/pages/css/codingzone/codingzone-main.css
Labels: refactor, feat, design

#383 [FE-#381] 경로 수정
  frontend/src/app/App.js
  frontend/src/pages/Coding-zone/CodingZoneAttendanceManager.js
  frontend/src/pages/Coding-zone/CodingZoneMain.js
  frontend/src/pages/Coding-zone/CodingZoneMyAttendance.js
  frontend/src/shared/ui/boardbar/CodingZoneBoardbar.js
  frontend/src/shared/ui/navigation/CodingZoneNavigation.js
Labels: feat

#387 [FE-#389] 수업 등록, 코딩존 설정 페이지 디폴트 행 추가
  frontend/src/pages/Coding-zone/CodingZoneRegist.js
  frontend/src/pages/Coding-zone/CodingZoneSetting.js
Labels: feat

#389 [FE-#388] 헤더 및 바디 부분 수정
  frontend/src/pages/Coding-zone/CodingZoneMain.js
  frontend/src/pages/css/codingzone/CodingClassRegist.css
  frontend/src/pages/css/codingzone/codingzone-main.css
  frontend/src/shared/ui/boardbar/CodingZoneBoardbar.css
  frontend/src/shared/ui/navigation/CodingZoneNavigation.css
  frontend/src/widgets/layout/Header/Navbar.css
Labels: feat, design

#408 [FE-#404] 코딩존 예약 페이지 반응형 구현
  frontend/src/pages/Coding-zone/CodingZoneMain.js
  frontend/src/pages/css/codingzone/codingzone-main.css
  frontend/src/shared/ui/navigation/CodingZoneNavigation.css
Labels: feat, design

#410 [FE-#409] 학생권한 코딩존 예약 페이지 반응형 구현
  frontend/src/pages/css/codingzone/codingzone-main.css
Labels: feat

#443 [FE-441] 2차 QA이후 버그 수정
  frontend/src/pages/Coding-zone/CodingZoneMain.js
  frontend/src/pages/css/codingzone/CodingClassRegist.css
  frontend/src/pages/css/codingzone/codingzone_attend.css
  frontend/src/shared/ui/boardbar/CodingZoneBoardbar.css
Labels: bug, design

#460 [FE-#459] 학생 조교의 출결 관리 반응형 UI 수정
  frontend/src/pages/Coding-zone/CodingZoneAttendanceAssistant.js
  frontend/src/pages/css/codingzone/codingzone_attend.css
  frontend/src/widgets/Calendar/CalendarInput.css
Labels: bug, design

#462 [FE-#461] 학생 조교의 출결석 버튼 로직 수정
  frontend/src/pages/Coding-zone/CodingZoneAttendanceAssistant.js
Labels: bug, refactor

#465 [FE-#464] 일반 학생의 출결 관리 페이지 반응형 UI 적용
  frontend/src/pages/css/codingzone/codingzone_attend.css
Labels: refactor, feat
