Repository ICE-AdvICE/advICE-web, pull requests merged in 2025-09, with the labels that each got.

#468 [FE-#464] 학생 조교의 출결 관리 표 반응형 UI 추가
  frontend/src/pages/css/codingzone/codingzone_attend.css
Labels: bug, refactor

#484 [FE-#482] 일반 학생의 출결 확인 페이지 반응형 UI 수정
  frontend/src/pages/Coding-zone/CodingZoneMyAttendance.js
  frontend/src/pages/css/codingzone/codingzone_attend.css
Labels: bug, refactor, design

#485 [FE-#483] 일반학생 권한 반응형
  frontend/src/pages/css/codingzone/codingzone-main.css
  frontend/src/shared/ui/Banner/Banner.css
Labels: bug
